/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedetail;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author riaydh
 */
public class login extends javax.swing.JFrame {

    Connection conn=null;
   ResultSet rs = null;
   PreparedStatement pst = null;
    public login() {
        initComponents();
        conn = db.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        t2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(t2);
        t2.setBounds(490, 230, 190, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(380, 180, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Artech Info System");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 80, 350, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(380, 240, 90, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Post");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 290, 40, 22);

        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(t1);
        t1.setBounds(490, 180, 190, 40);

        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setText("Create");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(580, 330, 100, 40);

        b2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b2.setText("login");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(490, 330, 80, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Employee Management");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 140, 279, 29);

        c1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Developer", "Associate", "HR" }));
        jPanel1.add(c1);
        c1.setBounds(490, 280, 190, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeedetail/Top-5-Apple-Desktop-Wallpapers_3.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 790, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
       try{
           int count=0;
           
           pst = conn.prepareStatement("select * from users where (username=? and password=? and division=?) ");
           pst.setString(1,t1.getText());
           pst.setString(2,t2.getText());
           pst.setString(3,c1.getSelectedItem().toString());
           rs = pst.executeQuery();
            while(rs.next()){
             int id = rs.getInt(1);
             Emp.empId = id;
             count = count+1;
           }
           String access = (c1.getSelectedItem().toString());
           if(access == "Admin"){
              if(count==1){
                JOptionPane.showMessageDialog(null, "Success");
                AdminPage ob  = new AdminPage();
                ob.setVisible(true);
                
                int value = Emp.empId;
            String reg = "insert into adit (emp_id,status) values ('"+value+"','Logged in')";
            pst = conn.prepareStatement(reg);
            pst.execute(); 
            this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Please insert the right Username & Password");
            }
           }
            if(access == "Developer"){
              if(count==1){
                JOptionPane.showMessageDialog(null, "Success");
                DeveloperPage developerpage  = new DeveloperPage();
                developerpage.setVisible(true);
               
                 int value = Emp.empId;
            String reg = "insert into adit (emp_id,status) values ('"+value+"','Logged in')";
            pst = conn.prepareStatement(reg);
            pst.execute(); 
            this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "Please insert the right Username & Password");
            }
           }
            if(access == "Associate"){
              if(count==1){
                JOptionPane.showMessageDialog(null, "Success");
                AssociatePage Associatepage  = new AssociatePage();
                Associatepage.setVisible(true);
               
                 int value = Emp.empId;
            String reg = "insert into adit (emp_id,status) values ('"+value+"','Logged in')";
            pst = conn.prepareStatement(reg);
            pst.execute(); 
            this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Please insert the right Username & Password");
            }
           }
            if(access == "HR"){
              if(count==1){
                JOptionPane.showMessageDialog(null, "Success");
                HrPage1 HRpage  = new HrPage1();
                HRpage.setVisible(true);
               
                int value = Emp.empId;
            String reg = "insert into adit (emp_id,status) values ('"+value+"','Logged in')";
            pst = conn.prepareStatement(reg);
            pst.execute(); 
            this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Please insert the right Username & Password");
            }
           }
          
       }catch(Exception e){
           JOptionPane.showMessageDialog(rootPane,"Failed" );
       }
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
      CreateUser CreateUser = new CreateUser();
      CreateUser.setVisible(true);
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables
}
